import "BindableBase.idl";
import "DelegateCommand.idl";

namespace ctrltest
{
    [bindable]
    [default_interface]
    runtimeclass MainPageViewModel 
    {
        MainPageViewModel();        
		Microsoft.UI.Xaml.Input.ICommand OnClickCommand{ get; };
    }
}
