namespace ctrltest
{
    [bindable]
    [default_interface]
    runtimeclass MainWindowViewModel 
    {
        MainWindowViewModel();
        String Title{ get; set; };
        Double TextSize{ get; };
        Microsoft.UI.Xaml.Input.ICommand OnClickCommand{ get; };        
    }
}
