import "MainViewModel.idl";

namespace ctrltest
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        MainViewModel ViewModel{ get; };
    }
}
